name: POSDAO Tests

on:
  push:
    tags:
    - '*'
    inputs:
      branch:
        description: 'Branch to get tests from'
        required: false
        default: 'master'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to get tests from'
        required: true
        default: 'master'

jobs:
  posdao-tests:
    name: Nethermind POSDAO Tests
    runs-on: ubuntu-latest
    steps:
    - name: Installing Linux packages
      run: |
        sudo apt-get update
        sudo apt-get install libsnappy-dev libc6-dev libc6
    - name: Cloning Nethermind repo
      run: |
        git clone https://github.com/NethermindEth/nethermind.git --recursive
        cd nethermind
        git submodule update --init src/rocksdb-sharp src/int256 src/Dirichlet
    - name: Cloning posdao-test-setup repo from Nethermind
      run: |
        git clone --branch ${{ github.event.inputs.branch }} https://github.com/NethermindEth/posdao-test-setup
    - name: Building Nethermind binary
      run: |
        cd nethermind
        mkdir bin
        cd src/Nethermind
        dotnet build Nethermind.sln -c Release
        cp -r Nethermind.Runner/bin/Release/netcoreapp3.1/* /home/runner/work/nethermind/nethermind/nethermind/bin/
    - name: Setup the Node.js
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '12'
    - name: Running POSDAO tests
      run: |
        cd posdao-test-setup
        npm run all-nethermind-no-watcher
